version: "3.5"

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    networks:
      - app-tier
    image: mysql:8.0.29
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
  server:
    networks:
      - app-tier
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
